### ISSUE TITLE
Memory error when downloading meta-information from TED youtube channel

### ISSUE THREAD

**Issue by mygithubcomments2017** [rg3/youtube-dl#15678]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer honestly
- Put an `x` into all the boxes [ ] relevant to your *issue* (like this: `[x]`)
- Use the *Preview* tab to see what your issue will actually look like

---

### Make sure you are using the *latest* version: run `youtube-dl --version` and ensure your version is *2018.02.11*. If it's not, read [this FAQ entry](https://github.com/rg3/youtube-dl/blob/master/README.md#how-do-i-update-youtube-dl) and update. Issues with outdated version will be rejected.
- [X] I've **verified** and **I assure** that I'm running youtube-dl **2018.02.11**

### Before submitting an *issue* make sure you have:
- [X] At least skimmed through the [README](https://github.com/rg3/youtube-dl/blob/master/README.md), **most notably** the [FAQ](https://github.com/rg3/youtube-dl#faq) and [BUGS](https://github.com/rg3/youtube-dl#bugs) sections
- [X] [Searched](https://github.com/rg3/youtube-dl/search?type=Issues) the bugtracker for similar issues including closed ones
- [X] Checked that provided video/audio/playlist URLs (if any) are alive and playable in a browser

### What is the purpose of your *issue*?
- [X] Bug report (encountered problems with youtube-dl)
- [ ] Site support request (request for adding support for a new site)
- [ ] Feature request (request for a new functionality)
- [X] Question
- [X] Other

---

### The following sections concretize particular purposed issues, you can erase any section (the contents between triple ---) not applicable to your *issue*

---
### Description of your *issue*, suggested solution and other information
`>` can a x64 version of youtube-dl.exe be released? I get:
```
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\__init__.py", line 471, in main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\__init__.py", line 461, in _real_main
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 1989, in download
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 857, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 796, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 995, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 857, in process_ie_result
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\YoutubeDL.py", line 785, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 440, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\youtube.py", line 1489, in _real_extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\youtube.py", line 252, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 634, in _download_webpage
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 543, in _download_webpage_handle
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\rg3\tmpy028tx8p\build\youtube_dl\extractor\common.py", line 620, in _webpage_read_content
MemoryError
```
with my query: 
`$ ./youtube-dl.exe --get-filename -o "{ 'title': '''%(title)s ''', 'date': '''%(upload_date)s''', 'views': '''%(view_count)s''', 'duration': '''%(duration)s''', 'url': '''https://www.youtube.com/watch?v=%(id)s''' }," https://www.youtube.com/user/TEDxTalks/videos | tee -a 'output_get_youtube_2_ted_1_4.txt'`

---
### If the purpose of this *issue* is a *bug report*, *site support request* or you are not completely sure provide the full verbose output as follows:

Add the `-v` flag to **your command line** you run youtube-dl with (`youtube-dl -v <your command line>`), copy the **whole** output and insert it here. It should look similar to one below (replace it with **your** log inserted between triple ```):

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', '--get-filename', '-o', "{ 'title': '''%(title)s ''', 'date': '''%(upload_date)s''', 'views': '''%(view_count)s''', 'duration': '''%(duration)s''', 'url': '''https://www.youtube.com/watch?v=%(id)s''' },", 'https://www.youtube.com/user/TEDxTalks/videos']
[debug] Encodings: locale cp1252, fs mbcs, out cp1252, pref cp1252
[debug] youtube-dl version 2018.02.11
[debug] Python version 3.4.4 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: none
[debug] Proxy map: {}
...
```

**Comment by dstftw** [comment]
Сonceptually it won't make any difference. What you should do is to extract playlist in parts using existing playlist options. Or extract each video separately on `--flat-playlist` results.
